### ISSUE TITLE
document the signup form process 

### ISSUE THREAD

**Issue by siparker** [afourmy/flask-gentelella#11]
I am struggling a bit to follow the process that the signup form uses.

I can see the route.py which pulls in the forms.py and makes an instance of the form 
`login_form = LoginForm(request.form)`
I can see the create user form has the 
`onclick="signup()"`
which it gets from static/build/js/login.js and that this posts the data to /create_user as json and if successful it simlautes a click on the login form.

what i dont get is where is the login submit going? I assume it posts to itself but i dont see how that is happening.

Could you summarise for me pls.

Sorry if these are noob questions im only a beginner.

Oh and is there a reason that the login page includes the js scripts inline in the body instead of in a scripts block?

**Comment by afourmy** [comment]
When you create a new user, it uses the `signup` javascript function to serialized the form data and send it to the `/create_user` endpoint.
The form data is serialized here: https://github.com/afourmy/flask-gentelella/blob/master/app/base/static/build/js/login.js#L15
and sent to the back-end via an Ajax request.
The back-end creates a new user in the database here: https://github.com/afourmy/flask-gentelella/blob/master/app/base/routes.py#L61-L66

The login page includes the js script in a script block, here: https://github.com/afourmy/flask-gentelella/blob/master/app/base/templates/login/login.html#L24

**Comment by caffeinatedMike** [comment]
@afourmy could you explain how/where I'm supposed to add the database credentials? 

I didn't know where to put the credentials, but figured I'd try creating a new user anyway. I was successful, but once I tried to login with the newly created account I ended up seeing a 403 error on the frontend, but saw a 200 status in in the python console.

Platform: Windows 7, Python 3.7

**Comment by afourmy** [comment]
Update some security parameters, can you try again now and reopen if it doesn't work ?
