### ISSUE TITLE
in cursor: raise errors.OperationalError("MySQL Connection not available.")

### ISSUE THREAD

**Issue by juliosouto** [afourmy/flask-gentelella#13]
If I set the db as a file in the disk, the template works fine, but setting up as a db in Pythonanywhere, I often get the error **"in cursor: raise errors.OperationalError("MySQL Connection not available.")"**.

Reloading the page once or twice works, but after a few minutes being idle, when I try to click to something, then it happens again. Over and over.

PS: the older website I had in Pythonanywhere used the same mySql configs and was working fine.

I just can't figure out what's happening. Do you know about this issue?

**Comment by afourmy** [comment]
Sorry I can't really help you, I've never used pythonanwyhere with a MySQL database, and flask-gentelella doesn't officially support MySQL (I provide the code for SQLite and PostgreSQL, and they work, but that's all).
If you manage to make it work somehow, you're welcome to send a PR showing the MySQL syntax in config.py

**Comment by tommydamiano** [comment]
Has this been resolved? I'm having the exact same issue now
