### ISSUE TITLE
can not add a new column in class User

### ISSUE THREAD

**Issue by HerrTeuer** [afourmy/flask-gentelella#15]
if I add a new column into User class in app/base/models.py 
```
class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)
    newcolumn = Column(String, unique=True)
```
I will get error that the database has no such column

> sqlalchemy.exc.OperationalError
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: User.newcolumn
> [SQL: SELECT "User".id AS "User_id", "User".username AS "User_username", "User".email AS "User_email", "User".password AS "User_password", "User".newcolumn AS "User_newcolumn" 
> FROM "User" 
> WHERE "User".id = ?
>  LIMIT ? OFFSET ?]
> [parameters: ('1', 1, 0)]
> (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by afourmy** [comment]
You cannot add new columns at runtime, you need to either migrate the database, or delete it and start with a fresh one.
I'll close as this is not related to this project.
