### ISSUE TITLE
How to run this project in Pycharm?

### ISSUE THREAD

**Issue by lisha992610** [afourmy/flask-gentelella#2]
Hi
My OS is Windows 10. 
I was able to run it successful in cmd by following those instruction. I am wondering how to run it in Pycharm? 

Thank you.

**Comment by afourmy** [comment]
Hello,

I don't use use Pycharm myself, so I've never done it before.

I think this is what you're looking for:
http://flask.pocoo.org/docs/dev/cli/#pycharm-integration
https://stackoverflow.com/questions/45741800/how-to-run-flask-app-as-a-package-in-pycharm
