### ISSUE TITLE
sqlalchemy cannot import name 'Binary'

### ISSUE THREAD

**Issue by jhui163** [afourmy/flask-gentelella#20]
my env is  windows 10 
flask run --host=0.0.0.0  ImportError was raised:
...
File "D:\flask-gentelella-master\app\base\models.py", line 3, in <module>
    from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary'

**Comment by mccarthysean** [comment]
Have you installed SQLAlchemy? If so, which version?

**Comment by blackwarriorxtn** [comment]
which version does work with this ?

**Comment by mccarthysean** [comment]
Try this instead, importing from `types`:

```python
from sqlalchemy import Column
from sqlalchemy.types import Binary, Integer, String
```

**Comment by afourmy** [comment]
changed it to LargeBinary, should be working now
