### ISSUE TITLE
paid theme on themeforest !

### ISSUE THREAD

**Issue by sandys** [afourmy/flask-gentelella#6]
hi,
your work is awesome! there are very few readymade flask admin templates out there. FYI, if you put this on themefores - there will be a lot of us who are willing to pay for it. 

thanks!

**Comment by afourmy** [comment]
Hi @sandys 

Just to be clear, I am not the author of gentelella, the front-end template that I'm using here. You can find the original template here: https://github.com/puikinsh/gentelella (there is also a link in the readme)
Gentelella is the front-end and what I did here is to add a Flask back-end, along with the whole CI/CD stuff (pytest, linting, selenium, docker, etc).

Both gentelella and flask-gentelella have a MIT license so they are completely free to use.

Thanks !
